#!/bin/bash
echo "--------------------------------------------------------------"
echo "                          setup64"
echo ""
echo "  richtet die Toolchain fuer ein 64-Bit Linux ein. Sollte"
echo "  dies faelschlicherweise aufgerufen worden sein und es sollte"
echo "  eine 32-Bit Toolchain eingerichtet werden, so einfach"
echo "  setup32 aufrufen"
echo "--------------------------------------------------------------"
rm -f -r ./tools/bin
mkdir -p ./tools/bin
cp ./tools/bin64/* ./tools/bin
echo ""
echo "... done"
echo ""
