# ---------------------------------------------
#  erzeugt charlie16_send
# ---------------------------------------------
all:
	make build

build:
	gcc charlie16_send.c minirs232.c -o charlie16_send

clean:
	rm -f *.o
	rm -f charlie16_send

