############################################################
#
#                         Makefile
#
############################################################

PROJECT       = charlie16_demo
MCU           = PFS154
MEMORG        = pdk14
F_CPU         = 8000000

# hier alle zusaetzlichen Softwaremodule angegeben
SRCS          = ../src/delay.rel
SRCS         += ../src/charlie16.rel

INC_DIR       = -I./ -I../include

include ../makefile.mk
