# ---------------------------------------------
#  erzeugt flash51n2 und flash51ide
# ---------------------------------------------
all:
	make build

build:
	fpc pfsprog.pas

clean:
	rm -f *.o
	rm -f *.ppu
	rm -f pfsprog

