############################################################
#
#                         Makefile
#
############################################################

PROJECT       = pfsreadhex

CC            = gcc

.PHONY: all clean

all: clean 
	$(CC) $(PROJECT).c -Os -lm -o $(PROJECT)

clean:
	rm -f $(PROJECT)
